### ISSUE TITLE
为什么我的Hotfix文件夹下的脚本GameEntry自动引用的ugf的，必须手动添加using Game

### ISSUE THREAD

**Issue by XiaoBojun** [GREAT1217/StarForce_HybridCLR#12]
我下载项目参考，修改我的项目，但我的项目Hotfix文件夹下的脚本中，GameEntry自动引用的ugf的，无法调用事件、资源等，必须手动添加using Game。但博主你的项目不需要，我想知道这是怎么设置的，我在unity改了脚本优先级也不行

**Comment by GREAT1217** [comment]
检查下项目中 Assets/Game/Scripts/Hotfix/Game.Hotfix 文件。如果没有，用 git revert 回来。

![image](https://github.com/GREAT1217/StarForce_HybridCLR/assets/34509649/81c9cefd-3541-42c4-9fdb-14f13ae51ecc)

**Comment by XiaoBojun** [comment]
你好，参照项目改的，但还是有这样问题
![image](https://github.com/GREAT1217/StarForce_HybridCLR/assets/81450802/7e4a9158-9123-44af-ab6a-0b29f366b66a)
![image](https://github.com/GREAT1217/StarForce_HybridCLR/assets/81450802/877b99b8-a122-4f67-a003-612fdf1904d8)
![image](https://github.com/GREAT1217/StarForce_HybridCLR/assets/81450802/bca32373-147f-4207-bcc1-74c6bfeba0ac)
![image](https://github.com/GREAT1217/StarForce_HybridCLR/assets/81450802/e68a5069-2841-497c-8bed-014c19ebdf18)

**Comment by GREAT1217** [comment]
因为我的命名空间是 Game、Game.Hotfix、Game.Editor，可以理解为存在父子级关系。

你的截图里，我没看到 SettingForm 的命名空间，如果是 Main.Hotfix 应该不会有错，如果是 HotFix.Runtime 那就需要调用 Main了。

**Comment by XiaoBojun** [comment]
我明白了，原来是这样，谢谢

**Comment by GREAT1217** [comment]
其次，我也没看到你的 Unity 是否有编译报错，如果 Unity 编译通过，VS 不通过，可以删除解决方案重新生成下 sln 。

**Comment by XiaoBojun** [comment]
嗯嗯，我知道怎么解决了，我不知道这个存在父子级关系
