### ISSUE TITLE
BuildPipeline.BuildPlayerInternalNoCheck 异常

### ISSUE THREAD

**Issue by BIGWGY** [GREAT1217/StarForce_HybridCLR#4]
![BD0IR1 IQ@ NGM7)@L34E{M](https://user-images.githubusercontent.com/13144389/183231984-42b7acd0-7312-49b2-90ee-99070b4742b8.png)

请问有遇过这个报错的吗？

**Comment by GREAT1217** [comment]
确定一下是否正确的安装了 HybridCLR。确定已安装，还有错误的话，清理 Library 文件夹试试。
![HybridCLR_Install](https://gitee.com/great1217/cdn/raw/master/images/HybridCLR_Install.png)

**Comment by GREAT1217** [comment]
不好意思，判断失误，这个问题是 il2cpp 地址环境变量导致的，已修复。另外，今天 hybridCLR 更新了部分 API，我已同步更新，注意使用 HybridCLR Builder 编辑器工具重新安装一遍

**Comment by BIGWGY** [comment]
嗯，收到了，谢谢了。
