### ISSUE TITLE
打包的Game.dll丢失

### ISSUE THREAD

**Issue by hkway168** [GREAT1217/StarForce_HybridCLR#8]
打包工具里的HotfixGame组包含的并不是Game.dll

**Comment by GREAT1217** [comment]
Game.dll 设计的是固定的流程，主要包含版本、资源检查和下载，不需要热更新。

热更的代码都在 Game.Hotfix.dll 中。

**Comment by hkway168** [comment]
如果需要更新要怎么操作呢，实际项目可能需要，里面还有二个UI的逻辑，是按照Game.Hotfix.dll写一套，还是直接删除Game.asmdef更好
